// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webApiTest.DataInfrastruture;

namespace webApiTest.DataInfrastructure.Migrations.AforeGlobal
{
    [DbContext(typeof(AforeGlobalContext))]
    [Migration("20200403090858_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("webApiTest.Domain.Posts.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 777, DateTimeKind.Local).AddTicks(3934),
                            Name = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2106),
                            Name = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2184),
                            Name = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2196),
                            Name = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2202),
                            Name = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2209),
                            Name = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2215),
                            Name = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2222),
                            Name = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2228),
                            Name = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 4, 3, 2, 8, 57, 782, DateTimeKind.Local).AddTicks(2235),
                            Name = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
